name: Cypress API Branch Tests
on:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows:
      ["first"]
    types:
      - completed
env:
  GITHUB_BRANCH_URL: https://develop-pricingtool.appspot.com/

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.10.0

    - name: Extract branch name
      shell: bash
      run : |
         echo toJSON(${{ github.event.pull_request }})
         BRANCH=${{github.head_ref}}
         BRANCH="${BRANCH////-}"
         echo "$BRANCH"
         echo "GITHUB_BRANCH=$BRANCH" >> $GITHUB_ENV
         
    - name: Create branch URL
      shell: bash
      if: "${{ env.GITHUB_BRANCH != '' }}"
      run : |
         URL=${{env.GITHUB_BRANCH}}
         URL=${URL:0:16}
         BRANCH_OUT="https://${{env.VERSION_VALUE}}-${URL}-dot-develop-pricingtool.nw.r.appspot.com"
         echo "GITHUB_BRANCH_URL=$BRANCH_OUT" >> $GITHUB_ENV

    - name: The
      shell: bash
      run : |    
         echo "$BRANCH"
         echo "GITHUB_BRANCH_URL" 
