name: Cypress API Branch Tests
on:
  workflow_run:
    workflows:
      ["first"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.10.0

    - name: Extract branch name
      shell: bash
      run : |
         BRANCH=${{github.event.pull_request.head.ref}}
         BRANCH="${BRANCH////-}"
         echo "GITHUB_BRANCH=$BRANCH" >> $GITHUB_ENV
