name: Cypress API Branch Tests
on:
  workflow_run:
    workflows:
      ["first"]
    types:
      - completed
env:
  GITHUB_BRANCH_URL: https://develop-pricingtool.appspot.com/

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.10.0

    - name: Extract branch name
      shell: bash
      run : |
         BRANCH=${{github.event.inputs.default_branch}}
         BRANCH="${BRANCH////-}"
         echo "$BRANCH"
         echo "GITHUB_BRANCH=$BRANCH" >> $GITHUB_ENV
         
    - name: Create branch URL
      shell: bash
      if: contains(env.GITHUB_BRANCH, 'develop')
      run : |
         URL=${{env.GITHUB_BRANCH}}
         URL=${URL:0:16}
         BRANCH_OUT="https://${{env.VERSION_VALUE}}-${URL}-dot-develop-pricingtool.nw.r.appspot.com"
         echo "GITHUB_BRANCH_URL=$BRANCH_OUT" >> $GITHUB_ENV
