name: Cypress API Branch Tests
concurrency: build
on: 
  workflow_dispatch:
  
env:
  GITHUB_BRANCH_URL: https://develop-pricingtool.appspot.com/

jobs:
 build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.10.0

    - name: Extract branch name
      shell: bash
      run : |
         BRANCH=${{github.event.pull_request.head.ref}}
         BRANCH="${BRANCH////-}"
         BRANCH="${BRANCH//_/-}"
         echo "GITHUB_BRANCH=$BRANCH" >> $GITHUB_ENV
    - name: Get current develop dataset version
      shell: bash 
      run: | 
         VALUE=v44
         echo "VERSION_VALUE=$VALUE" >> $GITHUB_ENV
         
    - name: Create branch URL
      shell: bash
      if: ${{!startsWith(github.event.pull_request.head.ref,'release')}}
      run : |
         URL=${{env.GITHUB_BRANCH}}
         URL=${URL:0:26}
         URL=${URL,,}
         BRANCH_OUT="https://${{env.VERSION_VALUE}}-${URL}-dot-develop-pricingtool.nw.r.appspot.com"
         echo "GITHUB_BRANCH_URL=$BRANCH_OUT" >> $GITHUB_ENV
         
  
    - name: The
      shell: bash
      run : |    
         echo "$BRANCH"
         echo ${GITHUB_REF##*/}
         echo ${GITHUB_REF}
         echo "$GITHUB_BRANCH_URL" 
